const mockBooks=[
  {"id": 1, "title": "To Kill a Mockingbird", "author": "Harper Lee", "genre": "fiction", "publishedAt": "1960-07-11", "pages": 281},
            {"id": 2, "title": "1984", "author": "George Orwell", "genre": "fiction", "publishedAt": "1949-06-08", "pages": 328},
            {"id": 3, "title": "Pride and Prejudice", "author": "Jane Austen", "genre": "romance", "publishedAt": "1813-01-28", "pages": 432},
            {"id": 4, "title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "genre": "fiction", "publishedAt": "1925-04-10", "pages": 180},
            {"id": 5, "title": "The Catcher in the Rye", "author": "J.D. Salinger", "genre": "fiction", "publishedAt": "1951-07-16", "pages": 277},
            {"id": 6, "title": "Lord of the Flies", "author": "William Golding", "genre": "fiction", "publishedAt": "1954-09-17", "pages": 224},
            {"id": 7, "title": "The Hobbit", "author": "J.R.R. Tolkien", "genre": "fantasy", "publishedAt": "1937-09-21", "pages": 310},
            {"id": 8, "title": "Fahrenheit 451", "author": "Ray Bradbury", "genre": "science fiction", "publishedAt": "1953-10-19", "pages": 249},
            {"id": 9, "title": "Jane Eyre", "author": "Charlotte Brontë", "genre": "romance", "publishedAt": "1847-10-16", "pages": 500},
            {"id": 10, "title": "Wuthering Heights", "author": "Emily Brontë", "genre": "romance", "publishedAt": "1847-12-01", "pages": 416},
            {"id": 11, "title": "The Chronicles of Narnia", "author": "C.S. Lewis", "genre": "fantasy", "publishedAt": "1950-10-16", "pages": 767},
            {"id": 12, "title": "Brave New World", "author": "Aldous Huxley", "genre": "science fiction", "publishedAt": "1932-08-30", "pages": 311},
            {"id": 13, "title": "The Kite Runner", "author": "Khaled Hosseini", "genre": "fiction", "publishedAt": "2003-05-29", "pages": 371},
            {"id": 14, "title": "Life of Pi", "author": "Yann Martel", "genre": "adventure", "publishedAt": "2001-09-11", "pages": 319},
            {"id": 15, "title": "The Book Thief", "author": "Markus Zusak", "genre": "historical fiction", "publishedAt": "2005-03-14", "pages": 552},
            {"id": 16, "title": "Gone with the Wind", "author": "Margaret Mitchell", "genre": "historical fiction", "publishedAt": "1936-06-30", "pages": 1037},
            {"id": 17, "title": "The Alchemist", "author": "Paulo Coelho", "genre": "fiction", "publishedAt": "1988-01-01", "pages": 163},
            {"id": 18, "title": "One Hundred Years of Solitude", "author": "Gabriel García Márquez", "genre": "magical realism", "publishedAt": "1967-06-05", "pages": 417},
            {"id": 19, "title": "The Lord of the Rings", "author": "J.R.R. Tolkien", "genre": "fantasy", "publishedAt": "1954-07-29", "pages": 1216},
            {"id": 20, "title": "Harry Potter and the Sorcerer's Stone", "author": "J.K. Rowling", "genre": "fantasy", "publishedAt": "1997-06-26", "pages": 309},
            {"id": 21, "title": "The Da Vinci Code", "author": "Dan Brown", "genre": "thriller", "publishedAt": "2003-03-18", "pages": 454},
            {"id": 22, "title": "The Girl with the Dragon Tattoo", "author": "Stieg Larsson", "genre": "thriller", "publishedAt": "2005-08-01", "pages": 672},
            {"id": 23, "title": "The Hunger Games", "author": "Suzanne Collins", "genre": "dystopian", "publishedAt": "2008-09-14", "pages": 374},
            {"id": 24, "title": "Twilight", "author": "Stephenie Meyer", "genre": "romance", "publishedAt": "2005-10-05", "pages": 498},
            {"id": 25, "title": "The Fault in Our Stars", "author": "John Green", "genre": "young adult", "publishedAt": "2012-01-10", "pages": 313},
            {"id": 26, "title": "A Game of Thrones", "author": "George R.R. Martin", "genre": "fantasy", "publishedAt": "1996-08-01", "pages": 694},
            {"id": 27, "title": "The Shining", "author": "Stephen King", "genre": "horror", "publishedAt": "1977-01-28", "pages": 447},
            {"id": 28, "title": "It", "author": "Stephen King", "genre": "horror", "publishedAt": "1986-09-15", "pages": 1138},
            {"id": 29, "title": "The Stand", "author": "Stephen King", "genre": "horror", "publishedAt": "1978-10-03", "pages": 1152},
            {"id": 30, "title": "Pet Sematary", "author": "Stephen King", "genre": "horror", "publishedAt": "1983-11-14", "pages": 374},
            {"id": 31, "title": "Dune", "author": "Frank Herbert", "genre": "science fiction", "publishedAt": "1965-08-01", "pages": 688},
            {"id": 32, "title": "Foundation", "author": "Isaac Asimov", "genre": "science fiction", "publishedAt": "1951-06-01", "pages": 244},
            {"id": 33, "title": "Ender's Game", "author": "Orson Scott Card", "genre": "science fiction", "publishedAt": "1985-08-01", "pages": 324},
            {"id": 34, "title": "The Martian", "author": "Andy Weir", "genre": "science fiction", "publishedAt": "2011-01-01", "pages": 369},
            {"id": 35, "title": "Ready Player One", "author": "Ernest Cline", "genre": "science fiction", "publishedAt": "2011-08-16", "pages": 374},
            {"id": 36, "title": "The Handmaid's Tale", "author": "Margaret Atwood", "genre": "dystopian", "publishedAt": "1985-08-17", "pages": 311},
            {"id": 37, "title": "Beloved", "author": "Toni Morrison", "genre": "historical fiction", "publishedAt": "1987-09-01", "pages": 324},
            {"id": 38, "title": "The Color Purple", "author": "Alice Walker", "genre": "fiction", "publishedAt": "1982-06-01", "pages": 295},
            {"id": 39, "title": "Invisible Man", "author": "Ralph Ellison", "genre": "fiction", "publishedAt": "1952-04-14", "pages": 581},
            {"id": 40, "title": "The Grapes of Wrath", "author": "John Steinbeck", "genre": "fiction", "publishedAt": "1939-04-14", "pages": 464},
            {"id": 41, "title": "Of Mice and Men", "author": "John Steinbeck", "genre": "fiction", "publishedAt": "1937-01-01", "pages": 107},
            {"id": 42, "title": "East of Eden", "author": "John Steinbeck", "genre": "fiction", "publishedAt": "1952-09-19", "pages": 601},
            {"id": 43, "title": "The Sun Also Rises", "author": "Ernest Hemingway", "genre": "fiction", "publishedAt": "1926-10-22", "pages": 251},
            {"id": 44, "title": "For Whom the Bell Tolls", "author": "Ernest Hemingway", "genre": "fiction", "publishedAt": "1940-10-21", "pages": 471},
            {"id": 45, "title": "A Farewell to Arms", "author": "Ernest Hemingway", "genre": "fiction", "publishedAt": "1929-09-27", "pages": 332},
            {"id": 46, "title": "The Old Man and the Sea", "author": "Ernest Hemingway", "genre": "fiction", "publishedAt": "1952-09-01", "pages": 127},
            {"id": 47, "title": "Catch-22", "author": "Joseph Heller", "genre": "fiction", "publishedAt": "1961-11-10", "pages": 453},
            {"id": 48, "title": "Slaughterhouse-Five", "author": "Kurt Vonnegut", "genre": "fiction", "publishedAt": "1969-03-31", "pages": 275},
            {"id": 49, "title": "One Flew Over the Cuckoo's Nest", "author": "Ken Kesey", "genre": "fiction", "publishedAt": "1962-02-01", "pages": 325},
            {"id": 50, "title": "On the Road", "author": "Jack Kerouac", "genre": "fiction", "publishedAt": "1957-09-05", "pages": 307}
  
]
export default mockBooks
